server:
  port: 8888
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - global-users
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:blogdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
#      schema-locations: classpath:db/db-schema.sql
#      data-locations: classpath:db/initial-data.sql
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 3
  servlet:
    multipart:
      max-file-size: 10MB
security:
  jwt:
    # validity time in minutes
    validity-time: 30
